# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramUploader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramUploader

  # Network
  pod 'Alamofire', '~> 5.0.0-rc.3'

  # Auto Layout Programmatically
  pod 'SnapKit', '~> 5.0.0'

  # Initializer
  pod 'Then'

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'InstagramUploaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
